/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class neildg_com_eagleeyesr_processing_jni_bridge_SuperResJNI */

#ifndef _Included_neildg_com_eagleeyesr_processing_jni_bridge_SuperResJNI
#define _Included_neildg_com_eagleeyesr_processing_jni_bridge_SuperResJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     neildg_com_eagleeyesr_processing_jni_bridge_SuperResJNI
 * Method:    n_processMat
 * Signature: (JJJ)J
 */
JNIEXPORT jlong JNICALL Java_neildg_com_eagleeyesr_processing_jni_1bridge_SuperResJNI_n_1processMat
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     neildg_com_eagleeyesr_processing_jni_bridge_SuperResJNI
 * Method:    n_testSum
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_neildg_com_eagleeyesr_processing_jni_1bridge_SuperResJNI_n_1testSum
  (JNIEnv *, jclass, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
