/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class neildg_com_megatronsr_MainActivity */

#ifndef _Included_neildg_com_megatronsr_MainActivity
#define _Included_neildg_com_megatronsr_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
JNIEXPORT jstring JNICALL Java_neildg_com_megatronsr_MainActivity_hello
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
